# Generated by Django 4.0.1 on 2022-01-17 14:22

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddIndex(
            model_name='name',
            index=django.contrib.postgres.indexes.HashIndex(fields=['email'], name='greeter_web_email_fe41db_hash'),
        ),
    ]
